apiVersion: v1
kind: Pod
metadata:
  name: web-test
  labels:
    app: web-test
spec:
  containers:
    - name: nginx-test
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - name: log-storage
          mountPath: /mnt
    
    - name: tomcat-test
      image: tomcat:alpine
      ports:
        - containerPort: 8080
      volumeMounts:
        - name: log-storage
          mountPath: /mnt

  volumes:
    - name: log-storage
      emptyDir: {}
