apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube100-site
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web-nginx
          image: nginx:1.13.0-alpine
          ports:
            - containerPort: 80
          livenessProbe: 
            httpGet: 
              path: /
              port: 80
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 5 
            periodSeconds:  5
          readinessProbe:
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 5

---

apiVersion: v1
kind: Service
metadata:
  name: k8s-svc-test
spec:
  ports:
    - port: 9001
      name: svc-nginx
      targetPort: 80
#    - port: 9002
#    #      name: svc-tomcat
#    #      targetPort: 8080
  selector:
    app: web
          
